name = "zzz-lore-wiki"
main = "src/worker.ts"
compatibility_date = "2026-09-11"

[assets]
directory = "./docs/.vitepress/dist"
binding = "ASSETS"
run_worker_first = true
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

[vars]
GITHUB_OWNER = "irohas3074"
GITHUB_REPO = "zzz-lore-wiki"
GITHUB_BRANCH = "main"
ADMIN_EMAIL = "irohas3074@gmail.com"
